PassBox/ViewComponents/AdminMenuViewComponent.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PassBox.Models;

namespace PassBox.ViewComponents;

public class AdminMenuViewComponent : ViewComponent
{
    private readonly UserManager<User> _userManager;

    public AdminMenuViewComponent(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var user = await _userManager.GetUserAsync(HttpContext.User); //The user that currently logged in
        var roles = await _userManager.GetRolesAsync(user);
        if (User == null)
            return Content("User not found");
        if (roles == null)
            return Content("Roles not found");
        return View(new UserWithRolesViewModel
        {
            User = user,
            Roles = roles
        });
    }
}

PassBox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>PassBox </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    @await Html.PartialAsync("_LayoutCssPartial")
    @await RenderSectionAsync("Styles",false)
</head>

<body>
    @await Component.InvokeAsync("AdminMenu")
    <!--page wrapper-->
    <div class="page-wrapper">
        <!-- Page Content-->
        <div class="page-content">
            @RenderBody()
            <footer class="footer text-center text-sm-left">
                &copy; @DateTime.Now.Year Sinan Fen.<span class="text-muted d-none d-sm-inline-block float-right">Crafted with <i class="mdi mdi-heart text-danger"></i> by Mannatthemes</span>
            </footer><!--end footer-->
        </div>
    </div>
    @await Html.PartialAsync("_LayoutJsPartial")
    @await RenderSectionAsync("Scripts",false)
</body>
</html>

PassBox/Views/Shared/_LayoutCssPartial.cshtml
<!-- App favicon -->
<link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/270/270008.png">

<!-- App css -->
<link href="~/crovexhtml/assets/css/jquery-ui.min.css" rel="stylesheet" />
<link href="~/crovexhtml/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="~/crovexhtml/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
<link href="~/crovexhtml/assets/css/metisMenu.min.css" rel="stylesheet" type="text/css" />
<link href="~/crovexhtml/assets/css/app.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous" />

PassBox/Views/Shared/_LayoutJsPartial.cshtml
  <!-- jQuery  -->
<script src="~/crovexhtml/assets/js/jquery.min.js"></script>
<script src="~/crovexhtml/assets/js/jquery-ui.min.js"></script>
<script src="~/crovexhtml/assets/js/bootstrap.bundle.min.js"></script>
<script src="~/crovexhtml/assets/js/metismenu.min.js"></script>
<script src="~/crovexhtml/assets/js/waves.js"></script>
<script src="~/crovexhtml/assets/js/feather.min.js"></script>
<script src="~/crovexhtml/assets/js/jquery.slimscroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@@11"></script>
<!-- App js -->
<script src="~/crovexhtml/assets/js/app.js"></script>